### PR TITLE
Termination nodes

### LINKED ISSUE #9: Add link & contracting page
- [x] Link to typeform
- [x] Change copy on front page to support 2 buttons: "I want to buy something" and "I need a contract". 
- [x] "I need a contract" page

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Changed font to Open Sans for better readability
- Added new termination node layout (see screenshot for details)
- Added start a PSA termination node
### Issues
- Fixes #9 (add link & contracting page)
### Screenshots

screen shot 2015-05-01 at 9 27 06 am
screen shot 2015-05-01 at 9 27 16 am

### CODE REVIEW

**Comment by msknee** [comment]
small style changes:
- [ ] background changed to white
- [ ] list has alternating medium gray (#E6E6E6) and light gray (#F2F2F2) colors

Otherwise good to go!

**Comment by bsmithgall** [comment]
The style was originally to match wexplorer, does that matter?

**Comment by bsmithgall** [comment]
screen shot 2015-05-04 at 11 11 10 am

**Comment by msknee** [comment]
Remove "start of process" from 1st bullet point

**Pull request merged**
